mybooks/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.indexView),
]

mybooks/books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("", views.indexView),
    path("<int:id>/", views.bookView, name="book"),
    path("add_book/", views.add_book),
    path("loan/<int:inventory_item_id>", views.loanView),
]

mybooks/bookseller/urls.py
from django.urls import path

from . import views

app_name = "bookseller"

urlpatterns = [
    path("", views.indexView),
    path("inventory/", views.inventoryView),
    path("inventory/add/", views.addInvetoryItemView),
    path(
        "inventory/<int:id>/delete", views.deleteInventoryView, name="inventory-delete"
    ),
]

mybooks/mybooks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include("app.urls")),
    path("", include("login.urls")),
    path("", include("register.urls")),
    path("client/", include("client.urls")),
    path("books/", include("books.urls")),
    path("bookseller/", include("bookseller.urls")),
    path("reading-groups/", include("reading_groups.urls")),
    path("loan/", include("loan.urls")),
    path("admin/", admin.site.urls),
    # path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

mybooks/books/models.py
from django.db import models

# Import the models from the other apps

# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Collection(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)

    title = models.CharField(max_length=100)
    cover = models.ImageField(upload_to="book_covers/")
    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.title

mybooks/books/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "cover", "publisher", "collection", "genre"]

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "input input-bordered"

mybooks/books/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from client.decorators import clients_only
from bookseller.models import Bookseller
from loan.models import InventoryItem, Loan
from .forms import BookForm
from .models import Book

# Create your views here.


def indexView(request):
    template = "books/index.html"

    books = Book.objects.all()

    context = {
        "books": books,
    }

    return render(request, template, context)


def bookView(request, id):
    template = "books/book.html"

    book = Book.objects.filter(id=id).first()

    bookItems = InventoryItem.objects.filter(book=book, quantity__gt=0)

    context = {
        "book": book,
        "bookItems": bookItems,
    }

    return render(request, template, context)


def add_book(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("books_list")
    else:
        form = BookForm()
    return render(request, "books/add_book.html", {"form": form})


@login_required
@clients_only
def loanView(request, inventory_item_id):
    client = request.client
    item = InventoryItem.objects.filter(id=inventory_item_id).first()

    loan = Loan.objects.create(
        client=client,
        item=item,
    )

    return render("/client")

mybooks/templates/books/add_book.html
{% extends 'base_client.html' %}


{% block main %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>
{% endblock %}

mybooks/templates/books/book.html
{% extends 'base_default.html' %}

{% block main %}

<a href="/books" class="btn btn-ghost mb-4">
    <i data-feather="arrow-left"></i>
    Back
</a>

{% if book %}
<div class="book flex items-start gap-4">
    <img src="/{{ book.cover }}" class="my-0 h-36" alt="">
    <div class="flex-1">
        <h6 class="card-title">
            {{ book.title }}
        </h6>
        <p>by {{ book.author.name }}, {{ book.publisher.name }}</p>
        <div>
            <div class="badge badge-outline">{{ book.collection.name }}</div>
            <div class="badge badge-outline">{{ book.genre }}</div>
        </div>
    </div>
</div>

<div class="booksellers">
    <table class="table w-full">
        <!-- head -->
        <thead>
            <tr>
                <th></th>
                <th>Bookseller</th>
                <th>Quantity</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <!-- row 1 -->
            {% for item in bookItems %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ item.inventory.bookseller.name }}</td>
                <td>{{ item.quantity }}</td>
                <td class="flex items-center gap-4">
                    <a href="{% url 'bookseller:inventory-delete' id=item.id %}">
                        <i data-feather="book-open"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

mybooks/templates/books/index.html
{% extends 'base_default.html' %}
{% load static %}

{% block main %}
<h1>Books</h1>

{% if user.is_bookseller %}
<a href="/books/add_book" class="btn btn-primary">
    <i data-feather="plus"></i>
    Add book
</a>
{% endif %}


<div class="books py-4 grid grid-cols-1 gap-4">
    {% for book in books %}
    <div class="book card card-side border shadow card-compact not-prose">
        <figure>
            <img src="/{{ book.cover }}" class="h-36" alt="">
        </figure>
        <a href="{% url 'books:book' id=book.id %}" class="no-underline">
            <div class="card-body">
                <h6 class="card-title">
                    {{ book.title }}
                </h6>
                <p>{{ book.author.name }}</p>
        </a>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}