mybooks/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.indexView),
]

mybooks/mybooks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include("app.urls")),
    path("", include("login.urls")),
    path("", include("register.urls")),
    path("client/", include("client.urls")),
    path("books/", include("books.urls")),
    path("bookseller/", include("bookseller.urls")),
    path("reading-groups/", include("reading_groups.urls")),
    path("loan/", include("loan.urls")),
    path("admin/", admin.site.urls),
    # path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

mybooks/reading_groups/urls.py
from django.urls import path
from . import views

app_name = "reading_groups"

urlpatterns = [
    path("", views.indexView),
    path("create/", views.createView),
    path("<int:id>/", views.detailView, name="detail"),
]

mybooks/reading_groups/models.py
from django.db import models
from bookseller.models import Bookseller

# Create your models here.


class ReadingGroup(models.Model):
    bookseller = models.ForeignKey(Bookseller, on_delete=models.CASCADE)

    title = models.CharField(max_length=256)
    capacity = models.IntegerField()
    description = models.CharField(max_length=4096)

    def __str__(self):
        return self.title

mybooks/reading_groups/forms.py
from django import forms


class ReadingGroupCreationForm(forms.Form):
    INPUT_ATTRS = {
        "class": "input input-bordered",
    }
    TEXTAREA_ATTRS = {
        "class": "input input-bordered h-36",
        "rows": 5,
    }

    title = forms.CharField(
        widget=forms.TextInput(INPUT_ATTRS),
        required=True,
    )
    capacity = forms.IntegerField(
        widget=forms.NumberInput(INPUT_ATTRS),
        required=True,
    )

    description = forms.CharField(
        widget=forms.Textarea(TEXTAREA_ATTRS),
        required=False,
    )

mybooks/reading_groups/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from bookseller.decorators import booksellers_only
from .forms import ReadingGroupCreationForm
from .models import ReadingGroup


# Create your views here.
def indexView(request):
    template = "reading_groups/index.html"

    reading_groups = ReadingGroup.objects.all()
    context = {
        "reading_groups": reading_groups,
    }

    return render(request, template, context)


def detailView(request, id):
    template = "reading_groups/detail.html"
    rg = ReadingGroup.objects.filter(id=id).first()
    context = {"rg": rg}

    return render(request, template, context)


@login_required
@booksellers_only
def createView(request):
    template = "reading_groups/create.html"

    if request.method == "POST":
        form = ReadingGroupCreationForm(request.POST)
        context = {
            "form": form,
        }

        if form.is_valid():
            title = form.cleaned_data["title"]
            capacity = form.cleaned_data["capacity"]

            bs = request.bookseller

            rg = ReadingGroup.objects.create(
                title=title,
                capacity=capacity,
                bookseller=bs,
            )

            return redirect(f"/reading-groups/{rg.id}")
        else:
            return render(request, template, context)

    form = ReadingGroupCreationForm()
    context = {
        "form": form,
    }

    return render(request, template, context)

mybooks/templates/reading_groups/create.html
{% extends 'base_default.html' %}

{% block main %}
<h1>
  Create a Reading group
</h1>

<form action="/reading-groups/create/" method="POST">
  {% csrf_token %}

  {% for field in form %}
  <div class="form-control">
    <label class="label">
      <span class="label-text">{{ field.label }}</span>
    </label>

    {{ field }}

    <label class="label">
      <span class="label-text-alt text-error font-bold">{{ field.errors.as_text }}</span>
    </label>
  </div>
  {% endfor %}

  <div class="form-control mt-8">
    <button type="submit" class="btn btn-primary btn-block">Create</button>
  </div>
</form>

{% endblock %}

mybooks/templates/reading_groups/detail.html
{% extends 'base_default.html' %}

{% block main %}

<a href="/reading-groups" class="btn btn-ghost">
  <i data-feather="arrow-left"></i>
  Back
</a>

<h1>
  Reading group
</h1>

{% if rg %}
<div class="reading-group">
  <h6>{{ rg.title }}</h6>
  <p>{{ rg.capacity }}</p>
</div>
{% endif %}
{% endblock %}

mybooks/templates/reading_groups/index.html
{% extends 'base_default.html' %}

{% block main %}
<h1>
  Reading groups
</h1>

<div class="py-2 border-y">
  {% if user.is_bookseller %}
  <a href="/reading-groups/create" class="btn btn-primary gap-2">
    <i data-feather="plus"></i>
    Create
  </a>
  {% endif %}
</div>

<div class="filters py-2 border-b">
  <span>Filter by:</span>
</div>

<div class="reading-groups py-4 grid grid-cols-1 gap-4">
  {% for rg in reading_groups %}
  <div class="reading-group card border shadow card-compact not-prose">
    <a href="{% url 'reading_groups:detail' id=rg.id %}" class="no-underline">
      <div class="card-body">
        <h6 class="card-title">
          {{ rg.title }}
        </h6>
        <p>{{ rg.bookseller.name }}</p>


        <div class="flex gap-2 items-center">
          <i data-feather="users"></i>
          <p>{{ rg.capacity }}</p>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}